### YamlMime:ManagedReference
items:
- uid: "fr.axa.automation.webengine.global.GlobalApplicationContext"
  id: "GlobalApplicationContext"
  parent: "fr.axa.automation.webengine.global"
  children:
  - "fr.axa.automation.webengine.global.GlobalApplicationContext.GlobalApplicationContext(fr.axa.automation.webengine.global.Settings,fr.axa.automation.webengine.generated.EnvironmentVariables,fr.axa.automation.webengine.generated.TestSuiteData,java.util.Map<java.lang.String,fr.axa.automation.webengine.core.TestCaseAdditionalInformation>)"
  - "fr.axa.automation.webengine.global.GlobalApplicationContext.getTestDataList()"
  langs:
  - "java"
  name: "GlobalApplicationContext"
  nameWithType: "GlobalApplicationContext"
  fullName: "fr.axa.automation.webengine.global.GlobalApplicationContext"
  type: "Class"
  package: "fr.axa.automation.webengine.global"
  syntax:
    content: "public class GlobalApplicationContext extends AbstractGlobalApplicationContext"
  inheritance:
  - "java.lang.Object"
  - "fr.axa.automation.webengine.global.AbstractGlobalApplicationContext"
  inheritedMembers:
  - "java.lang.Object.clone()"
  - "java.lang.Object.equals(java.lang.Object)"
  - "java.lang.Object.finalize()"
  - "java.lang.Object.getClass()"
  - "java.lang.Object.hashCode()"
  - "java.lang.Object.notify()"
  - "java.lang.Object.notifyAll()"
  - "java.lang.Object.toString()"
  - "java.lang.Object.wait()"
  - "java.lang.Object.wait(long)"
  - "java.lang.Object.wait(long,int)"
- uid: "fr.axa.automation.webengine.global.GlobalApplicationContext.GlobalApplicationContext(fr.axa.automation.webengine.global.Settings,fr.axa.automation.webengine.generated.EnvironmentVariables,fr.axa.automation.webengine.generated.TestSuiteData,java.util.Map<java.lang.String,fr.axa.automation.webengine.core.TestCaseAdditionalInformation>)"
  id: "GlobalApplicationContext(fr.axa.automation.webengine.global.Settings,fr.axa.automation.webengine.generated.EnvironmentVariables,fr.axa.automation.webengine.generated.TestSuiteData,java.util.Map<java.lang.String,fr.axa.automation.webengine.core.TestCaseAdditionalInformation>)"
  parent: "fr.axa.automation.webengine.global.GlobalApplicationContext"
  langs:
  - "java"
  name: "GlobalApplicationContext(Settings settings, EnvironmentVariables environmentVariables, TestSuiteData testSuiteData, Map<String,TestCaseAdditionalInformation> testCaseAdditionnalInformationList)"
  nameWithType: "GlobalApplicationContext.GlobalApplicationContext(Settings settings, EnvironmentVariables environmentVariables, TestSuiteData testSuiteData, Map<String,TestCaseAdditionalInformation> testCaseAdditionnalInformationList)"
  fullName: "fr.axa.automation.webengine.global.GlobalApplicationContext.GlobalApplicationContext(Settings settings, EnvironmentVariables environmentVariables, TestSuiteData testSuiteData, Map<String,TestCaseAdditionalInformation> testCaseAdditionnalInformationList)"
  overload: "fr.axa.automation.webengine.global.GlobalApplicationContext.GlobalApplicationContext*"
  type: "Constructor"
  package: "fr.axa.automation.webengine.global"
  syntax:
    content: "public GlobalApplicationContext(Settings settings, EnvironmentVariables environmentVariables, TestSuiteData testSuiteData, Map<String,TestCaseAdditionalInformation> testCaseAdditionnalInformationList)"
    parameters:
    - id: "settings"
      type: "fr.axa.automation.webengine.global.Settings"
    - id: "environmentVariables"
      type: "fr.axa.automation.webengine.generated.EnvironmentVariables"
    - id: "testSuiteData"
      type: "fr.axa.automation.webengine.generated.TestSuiteData"
    - id: "testCaseAdditionnalInformationList"
      type: "java.util.Map<java.lang.String,fr.axa.automation.webengine.core.TestCaseAdditionalInformation>"
- uid: "fr.axa.automation.webengine.global.GlobalApplicationContext.getTestDataList()"
  id: "getTestDataList()"
  parent: "fr.axa.automation.webengine.global.GlobalApplicationContext"
  langs:
  - "java"
  name: "getTestDataList()"
  nameWithType: "GlobalApplicationContext.getTestDataList()"
  fullName: "fr.axa.automation.webengine.global.GlobalApplicationContext.getTestDataList()"
  overload: "fr.axa.automation.webengine.global.GlobalApplicationContext.getTestDataList*"
  type: "Method"
  package: "fr.axa.automation.webengine.global"
  syntax:
    content: "public List<TestData> getTestDataList()"
    return:
      type: "java.util.List<fr.axa.automation.webengine.generated.TestData>"
references:
- uid: "fr.axa.automation.webengine.global.Settings"
  name: "Settings"
  nameWithType: "Settings"
  fullName: "fr.axa.automation.webengine.global.Settings"
- uid: "fr.axa.automation.webengine.generated.EnvironmentVariables"
  name: "EnvironmentVariables"
  nameWithType: "EnvironmentVariables"
  fullName: "fr.axa.automation.webengine.generated.EnvironmentVariables"
- uid: "fr.axa.automation.webengine.generated.TestSuiteData"
  name: "TestSuiteData"
  nameWithType: "TestSuiteData"
  fullName: "fr.axa.automation.webengine.generated.TestSuiteData"
- uid: "java.util.Map<java.lang.String,fr.axa.automation.webengine.core.TestCaseAdditionalInformation>"
  spec.java:
  - uid: "java.util.Map"
    name: "Map"
    fullName: "java.util.Map"
  - name: "<"
    fullName: "<"
  - uid: "java.lang.String"
    name: "String"
    fullName: "java.lang.String"
  - name: ","
    fullName: ","
  - uid: "fr.axa.automation.webengine.core.TestCaseAdditionalInformation"
    name: "TestCaseAdditionalInformation"
    fullName: "fr.axa.automation.webengine.core.TestCaseAdditionalInformation"
  - name: ">"
    fullName: ">"
- uid: "fr.axa.automation.webengine.global.GlobalApplicationContext.GlobalApplicationContext*"
  name: "GlobalApplicationContext"
  nameWithType: "GlobalApplicationContext.GlobalApplicationContext"
  fullName: "fr.axa.automation.webengine.global.GlobalApplicationContext.GlobalApplicationContext"
  package: "fr.axa.automation.webengine.global"
- uid: "java.util.List<fr.axa.automation.webengine.generated.TestData>"
  spec.java:
  - uid: "java.util.List"
    name: "List"
    fullName: "java.util.List"
  - name: "<"
    fullName: "<"
  - uid: "fr.axa.automation.webengine.generated.TestData"
    name: "TestData"
    fullName: "fr.axa.automation.webengine.generated.TestData"
  - name: ">"
    fullName: ">"
- uid: "fr.axa.automation.webengine.global.GlobalApplicationContext.getTestDataList*"
  name: "getTestDataList"
  nameWithType: "GlobalApplicationContext.getTestDataList"
  fullName: "fr.axa.automation.webengine.global.GlobalApplicationContext.getTestDataList"
  package: "fr.axa.automation.webengine.global"
- uid: "fr.axa.automation.webengine.global.AbstractGlobalApplicationContext"
  name: "AbstractGlobalApplicationContext"
  nameWithType: "AbstractGlobalApplicationContext"
  fullName: "fr.axa.automation.webengine.global.AbstractGlobalApplicationContext"
- uid: "java.lang.Object.notify()"
  name: "Object.notify()"
  nameWithType: "Object.notify()"
  fullName: "java.lang.Object.notify()"
- uid: "java.lang.Object.wait()"
  name: "Object.wait()"
  nameWithType: "Object.wait()"
  fullName: "java.lang.Object.wait()"
- uid: "java.lang.Object.finalize()"
  name: "Object.finalize()"
  nameWithType: "Object.finalize()"
  fullName: "java.lang.Object.finalize()"
- uid: "java.lang.Object.clone()"
  name: "Object.clone()"
  nameWithType: "Object.clone()"
  fullName: "java.lang.Object.clone()"
- uid: "java.lang.Object.notifyAll()"
  name: "Object.notifyAll()"
  nameWithType: "Object.notifyAll()"
  fullName: "java.lang.Object.notifyAll()"
- uid: "java.lang.Object.equals(java.lang.Object)"
  name: "Object.equals(Object)"
  nameWithType: "Object.equals(Object)"
  fullName: "java.lang.Object.equals(java.lang.Object)"
- uid: "java.lang.Object.getClass()"
  name: "Object.getClass()"
  nameWithType: "Object.getClass()"
  fullName: "java.lang.Object.getClass()"
- uid: "java.lang.Object.wait(long)"
  name: "Object.wait(long)"
  nameWithType: "Object.wait(long)"
  fullName: "java.lang.Object.wait(long)"
- uid: "java.lang.Object.hashCode()"
  name: "Object.hashCode()"
  nameWithType: "Object.hashCode()"
  fullName: "java.lang.Object.hashCode()"
- uid: "java.lang.Object.wait(long,int)"
  name: "Object.wait(long,int)"
  nameWithType: "Object.wait(long,int)"
  fullName: "java.lang.Object.wait(long,int)"
- uid: "java.lang.Object.toString()"
  name: "Object.toString()"
  nameWithType: "Object.toString()"
  fullName: "java.lang.Object.toString()"
- uid: "java.lang.String,fr.axa.automation.webengine.core.TestCaseAdditionalInformation"
  name: "String,TestCaseAdditionalInformation"
  nameWithType: "String,TestCaseAdditionalInformation"
  fullName: "java.lang.String,fr.axa.automation.webengine.core.TestCaseAdditionalInformation"
- uid: "java.util.Map"
  name: "Map"
  nameWithType: "Map"
  fullName: "java.util.Map"
- uid: "java.util.List"
  name: "List"
  nameWithType: "List"
  fullName: "java.util.List"
- uid: "fr.axa.automation.webengine.generated.TestData"
  name: "TestData"
  nameWithType: "TestData"
  fullName: "fr.axa.automation.webengine.generated.TestData"
